name: Code Quality
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install --upgrade pip

      # install ruff, mypy, black, and pytest
      - run: pip install ruff mypy black pytest
      - run: ruff check app
      - run: black --check app

      # install dependencies and test
      - run: pip install -r app/requirements.txt
      - run: pytest app
